### ISSUE TITLE
selenium.common.exceptions.WebDriverException session deleted because of page crash on most websites

### ISSUE THREAD

**Issue by Aurora25** [Lowess/vshot#1]
Hello, 

I'm using vshot to download webpages with their dynaically loaded content. For the majority of pages that I try, I see the following error:

```---> Vshot https://www.pensandpatron.com/lists/coyote-ugly-then-now-tb/?psl=g_c5afe5&c=0.1727
📺 Xvfb Listening on :99
📷 Running Vshot
Traceback (most recent call last):
  File "bin/vshot", line 94, in <module>
    output = engine.save_html(url=args.url)
  File "/src/lib/vshot/vshot.py", line 67, in save_html
    self._driver.get(url)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=87.0.4280.141)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/vshot", line 107, in <module>
    engine.teardown()
  File "/src/lib/vshot/vshot.py", line 55, in teardown
    self._driver.close()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
```

When copy-pasting the urls into my chrome browser the page loads fine. 

This is how I run it:

```
file=$1
for url in $(cat $file); do
    echo "---> Vshot ${url}"
    docker run -it --rm -v ~/.vshot:/root/.vshot lowess/vshot --url ${url} \
        --save-html \
        --save-s3 s3://bucket/prefix

done
```
I tried installing a new chromedriver with `brew install chromedriver`, and redownloading the entire image, but to no avail.

Googling the error I found this link: https://stackoverflow.com/questions/56483403/selenium-common-exceptions-webdriverexception-message-invalid-session-id-using, however it does not happen with every url.

Example:
```
---> Vshot https://gutefrage.net/frage/ist-es-normal-dass-ich-mit-einer-rx-580-8gb-ark-auf-mittleren-einstellungen-unter-30-fps-laeuft
📺 Xvfb Listening on :99
📷 Running Vshot
---> Vshot https://astrostyle.com/zodiac-signs/taurus-horoscope/?sscid=31k5_s2dxx
📺 Xvfb Listening on :99
📷 Running Vshot
Traceback (most recent call last):
  File "bin/vshot", line 107, in <module>
    engine.teardown()
  File "/src/lib/vshot/vshot.py", line 55, in teardown
    self._driver.close()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
```

**Comment by Lowess** [comment]
Hey @Aurora25 thanks for using Vshot 😎 and filing this ticket.

As per this stackoverflow threat https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot it seems that Chrome may crash on certain pages due to too small /dev/shm.

In order to workaround this limitation I would suggest adding `-v /dev/shm:/dev/shm` as a volume mount to the vshot container.

Here is an example without the volume mount:
```
$ docker run -it --rm  -v ~/.vshot:/root/.vshot lowess/vshot --url https://www.foodandwine.com/video/jacques-pépin-peeling-broccoli --save-html

📺 Xvfb Listening on :99
📷 Running Vshot
Traceback (most recent call last):
  File "bin/vshot", line 94, in <module>
    output = engine.save_html(url=args.url)
  File "/src/lib/vshot/vshot.py", line 72, in save_html
    f.write(self._driver.page_source)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=87.0.4280.141)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/vshot", line 107, in <module>
    engine.teardown()
  File "/src/lib/vshot/vshot.py", line 55, in teardown
    self._driver.close()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
```

With the /dev/shm volume mount:

```
$ docker run -it --rm -v /dev/shm:/dev/shm  -v ~/.vshot:/root/.vshot lowess/vshot --url https://www.foodandwine.com/video/jacques-pépin-peeling-broccoli --save-html
📺 Xvfb Listening on :99
📷 Running Vshot
$ ls ~/.vshot/shots/https%3A%2F%2Fwww.foodandwine.com%2Fvideo%2Fjacques-p%C3%A9pin-peeling-broccoli   
js-on-page.html
```

I will update the README instructions accordingly !
Thanks
